"""Governance: the generated API catalogue cannot silently drop a public name.

The reference site is generated by looping over ``gbfs_toolkit.__all__``
(``scripts/gen_ref_pages.py``). This asserts the invariants that generation relies
on, so a public object that the catalogue could not place fails CI here rather
than vanishing from the docs.
"""

import gbfs_toolkit as gb

CATEGORIES = {"audit", "analytics", "spatial", "io", "interfaces", "core"}


def test_all_is_unique_and_resolvable():
    names = list(gb.__all__)
    assert len(names) == len(set(names)), "duplicate names in __all__"
    for name in names:
        assert getattr(gb, name, None) is not None


def test_every_public_name_is_categorisable():
    # Mirrors scripts/gen_ref_pages.py::_category; every name must land in a category
    # (so it gets a generated page and a summary row).
    for name in gb.__all__:
        obj = getattr(gb, name)
        module = getattr(obj, "__module__", None) or getattr(obj, "__name__", "gbfs_toolkit")
        assert module.startswith("gbfs_toolkit"), f"{name} is not a gbfs_toolkit object"
        parts = module.split(".")
        key = parts[1] if len(parts) > 1 and parts[1] in CATEGORIES else "core"
        assert key in CATEGORIES
