"""Generate the API reference catalogue, driven by ``gbfs_toolkit.__all__``.

Run automatically by ``mkdocs-gen-files`` at build time. It produces one page per
public object plus a thematic summary landing. Because everything is generated by
looping over ``__all__``, the catalogue can never silently omit a public name: add
it to ``__all__`` and its page and summary row appear at the next build.
"""

from pathlib import Path

import mkdocs_gen_files

import gbfs_toolkit as gb

# Submodule -> human category (ordered as they should appear in the summary).
CATEGORIES = {
    "audit": "Audit (A1–A7)",
    "analytics": "Analytics",
    "spatial": "Spatial",
    "io": "Ingestion & I/O",
    "interfaces": "Interfaces",
    "core": "Core & schema",
}


def _category(name: str) -> str:
    obj = getattr(gb, name)
    module = getattr(obj, "__module__", None) or getattr(obj, "__name__", "gbfs_toolkit")
    parts = module.split(".")
    return parts[1] if len(parts) > 1 and parts[1] in CATEGORIES else "core"


def _summary_line(name: str) -> str:
    doc = (getattr(gb, name).__doc__ or "").strip()
    return doc.splitlines()[0] if doc else ""


nav = mkdocs_gen_files.Nav()
by_category: dict[str, list[str]] = {key: [] for key in CATEGORIES}

for name in sorted(gb.__all__, key=str.lower):
    key = _category(name)
    by_category[key].append(name)
    doc_path = Path("reference", key, f"{name}.md")
    with mkdocs_gen_files.open(doc_path, "w") as fd:
        fd.write(f"# {name}\n\n::: gbfs_toolkit.{name}\n")
    mkdocs_gen_files.set_edit_path(doc_path, Path("scripts/gen_ref_pages.py"))
    nav[(CATEGORIES[key], name)] = Path(key, f"{name}.md").as_posix()

# Thematic landing: one categorised table, function -> one-line summary.
with mkdocs_gen_files.open("reference/index.md", "w") as fd:
    fd.write("# API reference\n\n")
    fd.write(
        "Every public object, generated from `gbfs_toolkit.__all__` (so this catalogue "
        "is always complete). Use the search bar to jump straight to a function, or browse "
        "by theme below.\n\n"
    )
    for key, title in CATEGORIES.items():
        names = sorted(by_category[key], key=str.lower)
        if not names:
            continue
        fd.write(f"## {title}\n\n| Function | Summary |\n|---|---|\n")
        for name in names:
            fd.write(f"| [`{name}`]({key}/{name}.md) | {_summary_line(name)} |\n")
        fd.write("\n")

with mkdocs_gen_files.open("reference/SUMMARY.md", "w") as fd:
    fd.write("- [Overview](index.md)\n")
    fd.writelines(nav.build_literate_nav())
